### PR TITLE
Update translate.py

### PR DESCRIPTION
**Pull request by 2077DevWave**
Changing **header** and **url** variables to private variables 
Add the **detect_laguage** function to detect the language of texts 
Add comments for functions
Using the function of sending api request to Google translator to avoid repeating the code

### CODE REVIEW

**Comment by ixabolfazl** [comment]
Can you add usage details for the `detect_language` function in the `README.md` file?

**Comment by 2077DevWave** [comment]
yeah sure! there is it

**Comment by ixabolfazl** [comment]
also you must add this line :
`from .translate import detect_laguage`
to this file:
`etranslate/__init__.py
`

**Comment by 2077DevWave** [comment]
Is it necessary to update the `keyword` in the `setup.py`?

**Pull request merged**
